[features]
seeds = false
skip-lint = false
[programs.testnet]
token_swap = "2uwqgDaHuyyUx36e9LSaxRQStDfeMH1SrLQGo3xLSBWV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
